args_all <- commandArgs(trailingOnly = FALSE)
script_arg <- grep("^--file=", args_all, value = TRUE)
script_dir <- dirname(normalizePath(sub("^--file=", "", script_arg[[1L]]), mustWork = TRUE))
source(file.path(script_dir, "comparegroups_common.R"))
args <- cg_parse_args()
if (is.null(args$spec) || is.null(args$output)) cg_stop("Usage: audit_input.R --spec <table-spec.json> --output <audit.json>")
audit <- cg_audit(args$spec)
cg_write_json(audit, args$output)
cat("COMPAREGROUPS_AUDIT_OK output=", normalizePath(args$output, winslash = "/"), "\n", sep = "")
