args_all <- commandArgs(trailingOnly = FALSE)
script_arg <- grep("^--file=", args_all, value = TRUE)
script_dir <- dirname(normalizePath(sub("^--file=", "", script_arg[[1L]]), mustWork = TRUE))
source(file.path(script_dir, "comparegroups_common.R"))
args <- cg_parse_args()
if (is.null(args[["output-root"]]) || is.null(args$stem)) cg_stop("Usage: validate_comparegroups.R --output-root <directory> --stem <stem>")
result <- cg_validate_outputs(args[["output-root"]], args$stem)
cat(jsonlite::toJSON(result, auto_unbox = TRUE, pretty = TRUE), "\n")
if (!identical(result$decision, "PASS")) quit(status = 3L)
